# Generated by Django 4.1.3 on 2022-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(verbose_name='level')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
        ),
    ]
