# Generated by Django 4.1.3 on 2022-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0002_berries_cake_client_decor_inscription_shape_topping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='price'),
        ),
    ]
