# Generated by Django 4.1.3 on 2022-11-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0003_alter_cake_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cake_orders.berries', verbose_name='Berries for the cake'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cake_orders.decor', verbose_name='Decor for the cake'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cake_orders.inscription', verbose_name='Inscription for the cake'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
