# Generated by Django 4.1.3 on 2022-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0004_alter_cake_berries_alter_cake_decor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='inscription',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='inscription'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
