# Generated by Django 4.1.3 on 2022-11-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0005_alter_cake_inscription_delete_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
    ]
