# Generated by Django 4.1.3 on 2022-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0006_remove_cake_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='forecast_delivery_datetime',
            field=models.DateTimeField(verbose_name='forecast date and time of the delivery'),
        ),
    ]
