# Generated by Django 4.1.3 on 2022-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0007_alter_order_forecast_delivery_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tg_account',
            field=models.CharField(max_length=200, unique=True, verbose_name='telegram account for communication'),
        ),
    ]
