# Generated by Django 4.1.3 on 2022-11-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_orders', '0009_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price of the cake'),
        ),
    ]
